# Generated by Django 5.1.5 on 2025-02-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('CASH', 'Cash')], default='paypal', max_length=255),
        ),
    ]
